### ISSUE TITLE
Optimize page load by adding React suspense to components where necessary.

### ISSUE THREAD

**Issue by izaakwalz** [XcavateBlockchain/RealXDeal.Dapp#13]

**Comment by webplusai** [comment]
@izaakwalz would you give me some more details about the performance issues on loading? Like what's the current status (for example loading takes xxx seconds, which is too long) and how we want to improve that.

**Comment by izaakwalz** [comment]
when I open the website and try to navigate to another page E.G /dashboard, it takes 5 - 30 seconds to load the page and this is happening because we are making use of SSR to render the pages. The idea is to make the pages load on instant click or within 1- 2 seconds. how this can be archived is by using [code-splitting](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#1-code-splitting) or [lazy loading](https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading)
